version: '3'

services:
  base-summarization-module:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Summarization_Models/LexRank_v_1/Dockerfile
    image: base-summarization-module:latest

  preprocessing-module:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Preprocessing_Module/build/Dockerfile
    image: preprocessing-module:latest

  data-sink-module-final:
    platform: linux/amd64
    build:
      context: .
      dockerfile: DataSink/Dockerfile
    image: data-sink-module-final:latest