name: summarization-module-to-lambda

on:
  push:
    paths:
      - "Backend_build/Preprocessing_Module/build/**"
jobs:
  update-lambda:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Backend_build
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: ${{ github.ref }}
    - name: Build container
      run: |
        docker compose build preprocessing-module
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-central-1
    - name: Push2ECR
      id: ecr
      uses: jwalton/gh-ecr-push@v1
      with:
        access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        region: eu-central-1
        image: preprocessing-module:latest
    - name: Update lambda with image
      run: aws lambda update-function-code --function-name summaroo-preprocessing-module --image-uri 355622878315.dkr.ecr.eu-central-1.amazonaws.com/preprocessing-module:latest